config/routes.rb
Rails.application.routes.draw do
  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'
  get 'sign_out', to: 'sessions#destroy'
  get 'sign_up', to: 'users#new'

  resources :users, only: [:new, :destroy, :create]
  resources :articles, only: [:new, :create, :show, :edit, :update, :destroy] do
    resources :votes, only: [:new, :create, :destroy]
  end
  resources :categories, only: [:index, :new, :new, :create, :update, :show]

  root 'categories#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artcat.rb
class Artcat < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/article.rb
class Article < ApplicationRecord
  validates :author_id, :title, :content, presence: true
  validates :title, length: { minimum: 3 }
  validates :content, length: { minimum: 10 }

  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_one_attached :avatar
  has_many :artcats, dependent: :destroy
  has_many :categories, through: :artcats

  has_many :votes
  has_many :voters, through: :votes, class_name: 'User'

  scope :get_most_votes, -> { joins(:votes).group('articles.id').order('count(votes.id) desc').first }
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, uniqueness: true, length: { maximum: 10 }
  validates :priority, presence: true, inclusion: 1..5

  has_many :artcats, dependent: :destroy
  has_many :articles, -> { includes(:avatar_attachment).order('created_at desc') }, through: :artcats

  scope :for_navbar, -> { limit(5) }

  def first_article
    arr = articles.includes(:avatar_attachment).order(created_at: :desc).first
    arr
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, :username, :email, presence: true, length: { minimum: 3, maximum: 30 }
  validates :username, :email, uniqueness: true, presence: true

  has_many :articles, foreign_key: :author_id
  has_many :votes
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :article

  validates :user_id, uniqueness: { scope: :article_id }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  helper_method :user_signed_in?

  def current_user
    User.find_by(id: session[:user_id])
  end

  def user_signed_in?
    !current_user.nil?
  end

  private

  def authenticate_user!
    redirect_to sign_in_path unless current_user
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_article, only: %i[show update destroy]

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
    @categories = Category.all.map { |c| [c.name, c.id] }
  end

  def create
    @article = current_user.articles.new(article_params)
    @categories = Category.all.map { |c| [c.name, c.id] }

    if @article.save
      @article.categories << Category.find_by(id: params[:categories])
      flash[:success] = 'New article created!'
      redirect_to @article
    else
      flash[:error] = 'Something went wrong'
      render 'new'
    end
  end

  def show
    @votes = @article.votes.count
  end

  def edit
    @article = Article.find(params[:id])
    @categories = Category.all.map { |c| [c.name, c.id] }
  end

  def update
    @categories = Category.all.map { |c| [c.name, c.id] }
    if @article.update(article_params)
      @article.artcats.first.delete
      @article.categories << Category.find_by(id: params[:categories])
      flash[:success] = 'Article was successfully updated'
      redirect_to @article
    else
      flash[:error] = 'Something went wrong'
      render 'edit'
    end
  end

  def destroy
    if @article.destroy
      flash[:success] = 'Article was successfully deleted.'
    else
      flash[:error] = 'Something went wrong'
    end
    redirect_to root_url
  end

  private

  def article_params
    params.require(:article).permit(:title, :content, :avatar)
  end

  def find_article
    @article = Article.find(params[:id])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!, only: %i[create new]
  before_action :find_category, only: %i[show edit update]

  def index
    # @categories = Category.all.order(priority: :desc)
    @categories = Category.all.includes(:articles).order(priority: :desc)
    @voted_article = Article.includes([:avatar_attachment]).get_most_votes
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = 'Category successfully created'
      redirect_to categories_path
    else
      flash[:error] = 'Something went wrong'
      render 'new'
    end
  end

  def show
    @articles = @category.articles
  end

  def edit; end

  def update
    if @category.update_attributes(category_params)
      flash[:success] = 'Category was successfully updated'
      redirect_to @category
    else
      flash[:error] = 'Something went wrong'
      render 'edit'
    end
  end

  private

  def category_params
    params.require(:category).permit(:name, :priority)
  end

  def find_category
    @category = Category.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by_username(params[:username])
    if user
      session[:user_id] = user.id
      redirect_to root_path, flash: { success: 'Successfully logged-in!' }
    else
      redirect_to sign_in_path, flash: { errors: "Username doesn't exist" }
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, flash: { errors: 'Good bye!' }
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = 'User successfully created'
      session[:user_id] = @user.id
      redirect_to root_url
    else
      flash[:error] = 'Something went wrong'
      render 'new'
    end
  end

  def destroy; end

  private

  def user_params
    params.require(:user).permit(:name, :username, :email)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :authenticate_user!

  def new; end

  def create
    @vote = current_user.votes.new(article_id: params[:article_id])

    if @vote.save
      flash[:success] = 'Vote successfully created'
    else
      flash[:error] = 'Something went wrong'
    end
    redirect_to root_url
  end

  def destroy
    @vote = Vote.find_by(article_id: params[:article_id], user_id: current_user.id)
    if @vote.delete
      flash[:success] = 'Vote was successfully deleted.'
    else
      flash[:error] = 'Something went wrong'
    end
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def display_vote(article)
    if user_signed_in?
      vote_unvote(article)
    else
      link_to article_votes_path(article_id: article.id), method: :post do
        raw '<i class="fas fa-thumbs-up fa-thumbs"></i>'
      end
    end
  end

  def vote_unvote(article)
    @vote = Vote.find_by(user_id: current_user.id, article_id: article.id)

    if @vote
      link_to article_vote_path(article_id: article.id, id: @vote.id), class: 'card__vote', method: :delete do
        raw '<i class="fas fa-thumbs-down fa-thumbs"></i>'
      end
    else
      link_to article_votes_path(article_id: article.id), method: :post do
        raw '<i class="fas fa-thumbs-up fa-thumbs"></i>'
      end
    end
  end

  def display_image(image)
    if image.avatar.attached?
      image.avatar
    elsif image.cover
      image.cover.to_s
    else
      'default-image.jpg'
    end
  end

  def first_article_category(category)
    first_article = category.articles.first
    if first_article.avatar.attached?
      first_article.avatar
    else
      first_article.cover.to_s
    end
  end

  def writer_user?(article_writer)
    return true if current_user.id == article_writer.author.id
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
  include ArticlesHelper

  def categories
    Category.for_navbar
  end

  def truncated_card_content(content)
    truncated_text = content.split(' ')[0..30].join(' ')
    "#{truncated_text}..."
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/articles/_article_form.html.erb
<div class="form-container">
<%= render partial: 'common/errors', locals: {msgs: @article} %>
  <%= form_with model: @article, class: 'form' do |f| %>
    <div class="control">
      <%= f.label :title, class: 'label | text-is-white' %>
      <%= f.text_field :title, class: 'input' %>
    </div>
    <div class="control">
      <%= f.label :content, class: 'label | text-is-white' %>
      <%= f.text_area :content, size: "25x9" ,class: 'input-area' %>
    </div>
  <div class="control">
      <%= f.label :cover, class: 'label | text-is-white' %>
      <%= f.file_field :avatar, class: 'input' %>
    </div>
  <div class="control">
      <%= f.label :category, class: 'label | text-is-white' %>
      <%= select_tag :categories, options_for_select(@categories), class: 'input' %>
    </div>
    <%= f.submit class: 'form__button | text-is-white' %>
  <% end %>
</div>

app/views/articles/edit.html.erb
<%= render 'article_form' %>

app/views/articles/new.html.erb
<%= render 'article_form' %>

app/views/articles/show.html.erb
  <article class="art-card">
    <div class="art-card__img">
      <%= image_tag(url_for(display_image(@article))) %>
    </div>
    <h2 class="art-card__title">
      <%= @article.title %>
      <p class="art-card__category">
        <%= @article.categories.first.name %>
      </p>
    </h2>
    <div class="art-card__likes">
      <%= vote_unvote(@article) %>
      <p>
        <%= @votes %>
        <span>votes</span>
      </p>
    </div>
    <p class="art-card__content">
      <%= @article.content %>
    </p>
    <div class="art-card__footer">
      <p class="art-card__author">
        Article Written by
        <span><%= @article.author.name %></span>
      </p>
      <div class="art-card__buttons">
        <%= link_to 'back', category_path(@article.categories.first.id), class: 'art-card__button-link btn-regular' %>
        <% if writer_user?(@article)%>
        <%= link_to 'Edit', edit_article_path(@article.id), class: 'art-card__button-link btn-warning' %>
        <%= link_to 'Delete', article_path(@article.id), method: :delete, class: 'art-card__button-link btn-danger' %>
        <% end %>
      </div>
    </div>
  </article>

app/views/categories/_categories.html.erb
  <section class="category-container">
    <% @categories.each do |cat| %>
      <% if !cat.articles.empty? %>
        <div class="category-card">
          <%= link_to category_path(cat) do %>
            <%= image_tag(url_for(first_article_category(cat))) %>
              <h2 class="category-card__name">
                <%= cat.name %>
              </h2>
              <h3 class="category-card__title">
                <%= cat.articles.first.title %>
              </h3>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </section>

app/views/categories/_category_form.html.erb
<div class="form-container">
  <%= render partial: 'common/errors', locals: {msgs: @category} %>
  <%= form_with model: @category, class: 'form' do |f| %>
    <div class="control">
      <%= f.label :name, class: 'label | text-is-white' %>
      <%= f.text_field :name, class: 'input' %>
    </div>
    <div class="control">
      <%= f.label :priority, class: 'label | text-is-white' %>
      <%= f.select :priority, [1, 2, 3, 4, 5], class: 'input' %>
    </div>
    <%= f.submit class: 'form__button | text-is-white' %>
  <% end %>
</div>

app/views/categories/_header.html.erb
<%= render 'common/flash' %>
<div class="banner">
  <%= link_to article_path(@voted_article) do %>
  <%= image_tag(url_for(display_image(@voted_article)), class: 'banner__img') %>
  <div class="banner__content">
    <h1 class="banner__content-title">
      <%= @voted_article.title %>
    </h1>
    <p class="banner__content-description">
      <%= truncated_card_content(@voted_article.content) %>
    </p>
  </div>
  <% end %>
</div>

app/views/categories/edit.html.erb
<%= render 'category_form' %>

app/views/categories/index.html.erb
<main>
  <%= render 'header' %>

  <%= render 'categories' %>
</main>

app/views/categories/new.html.erb
<%= render 'category_form' %>

app/views/categories/show.html.erb
<div class="card-container">
  <% @articles.each do |art| %>
    <article class="card">
      <%= image_tag(url_for(display_image(art)), class: 'card__image') %>
      <div class="card__info">
        <h2 class="card__title">
          <%= @category.name%>
        </h2>
        <div class="card__subtitle">
          <%= art.title %>
        </div>
        <div>
          <p class="card__content">
            <%= truncated_card_content(art.content) %>
          </p>
            <%= link_to 'Read more', article_path(art.id), class: 'card__read-more' %>
        </div>
        <div class='card__vote'>
          <%= display_vote(art) %>
          <span>
            <%= art.votes.count %>
            votes
          </span>
        </div>
      </div>
    </article>
  <% end %>
</div>

app/views/common/_errors.html.erb
<% if msgs.errors.any? %>
    <ul class="errors_list">
      <% msgs.errors.full_messages.each do |msg| %>
        <li class="errors_list-item"><%= msg %></li>
      <% end%>
    </ul>
  <% end %>

app/views/common/_flash.html.erb
      <% flash.each do |key, value| %>
        <%= content_tag :p, value, class: "flash-#{key}" %>
      <% end %>

app/views/common/_footer.html.erb
<footer class="footer">
  <div class="footer__start">
    <%= link_to 'MoviesLife', categories_path, class: 'footer__logo' %>
  </div>
  <div class="footer__middle">
    <p>Design by Kevin</p>
  </div>
  <div class="footer__end">
    <span>contact with me:</span>
    <ul class="footer__social">
      <li>
        <a href="https://github.com/kcotrinam" class="footer__social-link">
          <i class="fab fa-github"></i>
        </a>
      </li>
      <li>
        <a href="https://www.linkedin.com/in/kevincotrina/" class="footer__social-link">
          <i class="fab fa-linkedin-in"></i>
        </a>
      </li>
      <li>
        <a href="https://twitter.com/kcotrinam_dev" class="footer__social-link">
          <i class="fab fa-twitter"></i>
        </a>
      </li>
    </ul>
  </div>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar">
  <div class="navbar__start">
      <%= link_to 'MoviesLife', categories_path, class: 'navbar__brand' %>
  </div>
  <div class="navbar__middle">
    <%= link_to 'New Article', new_article_path, class: 'navbar__new-article' %>
    <%= link_to 'New category', new_category_path, class: 'navbar-item' %>
    <div class="categories | dropdown">
        categories
      <div class="categories | dropdown-items">
        <% categories.each do |cat| %>
            <%= link_to "#{cat.name}", category_path(cat), class: 'navbar__middle-link | ' %>
        <% end %>
      </div>
    </div>

  </div>

  <div class="navbar__end">
    <% if user_signed_in?%>
      <p class="navbar__end-user">
        <%= current_user.name %>
      </p>
        <%= link_to 'Sign out', sign_out_path, class: 'navbar-item' %>
    <% else %>
        <%= link_to 'Sign up', sign_up_path, class: "button is-primary" %>
        <%= link_to 'Sign in', sign_in_path, class: "navbar-item" %>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieLife</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,700;0,900;1,100;1,300;1,400;1,700&display=swap" rel="stylesheet">

  </head>

  <body>
    <div class="main">
      <%= render 'common/navbar' %>
      
      <%= yield %>

      <%= render 'common/footer' %>
    </div>
  </body>
</html>

app/views/users/_errors.html.erb
<% if @user.errors.any? %>
    <ul class="errors_list">
      <% @user.errors.full_messages.each do |msg| %>
        <li class="errors_list-item"><%= msg %></li>
      <% end%>
    </ul>
  <% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/new.html.erb
 

<div class="form-container">
  <%= render partial: 'common/errors', locals: {msgs: @user} %>
  <%= form_with model: @user, class: 'form' do |f| %>
    <div class="control">
      <%= f.label :name, class: "label | text-is-white" %>
      <%= f.text_field :name, class: "input" %>
    </div>
    <div class="control">
      <%= f.label :username, class: "label | text-is-white" %>
      <%= f.text_field :username, class: "input" %>
    </div>
    <div class="control">
      <%= f.label :email, class: "label | text-is-white" %>
      <%= f.text_field :email, class: "input" %>
    </div>
    <%= f.submit class: "form__button | text-is-white" %>
  <% end %>
</div>

app/views/votes/create.html.erb
<h1>Votes#create</h1>
<p>Find me in app/views/votes/create.html.erb</p>

app/views/votes/destroy.html.erb
<h1>Votes#destroy</h1>
<p>Find me in app/views/votes/destroy.html.erb</p>

app/views/votes/new.html.erb
<h1>Votes#new</h1>
<p>Find me in app/views/votes/new.html.erb</p>